#!/bin/bash
#!usr/bin/env bash
echo 'put the name of file: '
read name
touch $name
echo 'put the code: '
read code

if [ $name != README.md ]; then
        echo -e '#!/bin/bash\n'$code >> $name
else
	echo -e $code >> $name
fi

chmod u+x $name
cat $name
git add .
echo 'put the msg: '
read txt
ter="'"$txt"'"
git commit -m$ter
git push
