#!/bin/bash
#!usr/bin/env bash

echo 'put the name of file: '
read name
touch $name
echo 'put the code: '

read code

if [$name != README.md]; then

	echo -e $code >> $name
else
	echo -e '#!/bin/bash\n'$code >> $name

fi

chmod u+x $name
cat $name
git add .
echo 'put the msg: '
read txt
git commit -m$txt
git push
